[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "obs-sdk"
version = "0.1.0"
description = "Observability SDK for OpenTelemetry"
authors = [{ name = "mohan"}]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}